version: '3.8'

services:
  database:
    image: postgres:13
    environment:
      POSTGRES_DB: loyalty
      POSTGRES_USER: loyalty_user
      POSTGRES_PASSWORD: loyalty_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U loyalty"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  postgres_data: